Repository ros2/ros2, pull requests merged in 2018-08, with the labels that each got.

#557 Add crystal milestone and descriptions to labels
  update_labels_github.py
Labels: enhancement, in review

#558 add rosidl_typesupport_fastrtps
  ros2.repos
Labels: in review

#564 Crystal release December 14
  update_labels_github.py
Labels: in progress

#565 update tags for bouncy patch 2
  ros2.repos
Labels: in review
