Repository ros2/ros2, pull requests merged in 2020-07, with the labels that each got.

#967 update rqt_publisher branch on master
  ros2.repos
Labels: bug

#964 update rqt_publisher branch for Foxy
  ros2.repos
Labels: bug

#965 update rqt_publisher branch for Eloquent
  ros2.repos
Labels: bug

#966 update rqt_publisher branch for Dashing
  ros2.repos
Labels: bug

#976 Add ros2cli_common_extensions metapackage
  ros2.repos
Labels: enhancement, in review

#977 [foxy] Add ros2cli common extensions metapackage
  ros2.repos
Labels: enhancement

#978 Add the 'google_benchmark_vendor' package
  ros2.repos
Labels: enhancement, in review

#983 Add the 'performance_test_fixture' repository
  ros2.repos
Labels: enhancement, in review
